### PR TITLE
[Fix] Aura Skills not recognizing Wand modified Blocks

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
Atm auraskills (previously aurelium skills) does not recognize when a fill wand or sponge wand modifies blocks. This just corrects that.

## Changes
- Added `AuraSkillsCompat`
  - This just has a method to add the placed block, I have this in a separate file that way the server won’t error if AuraSkills is not present
- Added `Utils#isAuraSkillsLoaded`
- Added auraskills bukkit api to `pom.xml`
- Added `AuraSkills` as softdepend to `plugin.yml`
  - I also went ahead and removed the template comments from this file, I can revert this change If you’d like though

## Testing
I just need to test that this does indeed work on servers with and without aurelium skills, I’ll let you know once I have :+1:

### CODE REVIEW

**Comment by GallowsDove** [comment]
What exactly is this good for? Because if it's for gaining experience (I'm not familiar with the plugin), then I'm not sure whether it should count as it would make gaining experience significantly easier

**Comment by JustAHuman-xD** [comment]
> What exactly is this good for? Because if it's for gaining experience (I'm not familiar with the plugin), then I'm not sure whether it should count as it would make gaining experience significantly easier

This does the opposite, currently you can use the fill wands to gain exp significantly easier, this corrects that and makes any blocks placed by the fill wand count as placed by a player, therefor making them not grant experience upon mining.

**Comment by JustAHuman-xD** [comment]
Can confirm this worked!
Previously blocks placed by the fill wand granted exp (which I confirmed)
With a build from this PR blocks placed did not grant exp! (which I also confirmed)

**Comment by GallowsDove** [comment]
Totally my bad, I forgot about this project because of some real life stuff. Should have pinged me! I'm sorry

**Pull request merged**
